[package]
 name = "square_api"
 version = "0.1.0"
 edition = "2021"

[dependencies]
 serde = "1.0.142"
 openapi-struct-gen = "*"

[build-dependencies]
 openapi-struct-gen = { version = "*", features = ["build"] }

[dependencies.indexmap]
 version = ">=1.6.1, <3.0.0"
 features = ["serde"]
