[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#  square_api = { version = "0.1.0", path = "../../sw/square_api", optional = true }
square_api = { version = "0.1.0", git = "https://github.com/pscott31/square_api", optional = true }
uuid = { version = "1.5.0", features = ["v4", "js"] }
email_address = "0.2.4"
reqwest = { version = "0.11.22", features = ["json"] }
rust_decimal = "1.33.0"
rust_decimal_macros = "1.33.0"
indexmap = "2.1.0"
leptos_icons = { version = "0.1.0", features = [
    "FaEnvelopeSolid",
    "FaTriangleExclamationSolid",
    "FaCheckSolid",
    "FaPlusSolid",
    "FaTrashSolid",
    "FaUserSolid",
    "FaPhoneSolid",
    "FaBasketShoppingSolid",
] }
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }

http.workspace = true
cfg-if.workspace = true
thiserror.workspace = true
serde = "1.0.193"
sanitizer = "0.1.6"
log.workspace = true
validator = { version = "0.16.1", features = ["derive", "phone"] }
phonenumber = "0.3.3"
convert_case = "0.6.0"
anyhow = "1.0.75"
dotenv = "0.15.0"
futures = "0.3.29"
css-inline = { version = "0.11.0", optional = true }
pluralizer = { version = "0.4.0", optional = true }
mail-send = { version = "0.4.2", optional = true }
axum = { workspace = true, optional = true }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:leptos_axum",
    "dep:square_api",
    "dep:css-inline",
    "dep:pluralizer",
    "dep:mail-send",
    "dep:axum",

]
default = []
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
